# Your bot TOKEN
token: TOKEN

# Telegram API ID & hash
api_id: 123456789
api_hash: HASH

# admin user IDs
admins:
  - 123456789
  - 987654321

# database settings
database:
  # acceptable types are 'sqlite3' and 'mysql'
  type: sqlite3
  name: loversbot

  # These are only required for mysql 
  # host: localhost
  # port: 3306
  # user: root
  # password: Apple.ali.p1384

# the bot's groups which bot have to manage
# other groups cannot use this bot
groups:
  - -100123456789
